### ISSUE TITLE
ttributeError: 'weakref' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by upidea** [sha256/python-var-dump#4]
(FlaskEnv)[bud@dev tests]$ nosetests -s test_models.py
#0 list(2) 
    [0] => object(User) (14)
        openid => NoneType(None) 
        activation_key => NoneType(None) 
        _sa_instance_state => object(InstanceState) (12)
E
======================================================================
ERROR: test_get_current_time (tests.test_models.TestUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bud/py/fbone/tests/test_models.py", line 12, in test_get_current_time
    var_dump(User.query.all())
  File "/home/bud/.pyenv/versions/FlaskEnv/lib/python2.7/site-packages/var_dump/_var_dump.py", line 79, in var_dump
    dump(x, 0, i, '', object)
  File "/home/bud/.pyenv/versions/FlaskEnv/lib/python2.7/site-packages/var_dump/_var_dump.py", line 68, in dump
    dump(i, space, num, '', typ)
  File "/home/bud/.pyenv/versions/FlaskEnv/lib/python2.7/site-packages/var_dump/_var_dump.py", line 66, in dump
    dump(o[i], space, num, i, typ)
  File "/home/bud/.pyenv/versions/FlaskEnv/lib/python2.7/site-packages/var_dump/_var_dump.py", line 66, in dump
    dump(o[i], space, num, i, typ)
  File "/home/bud/.pyenv/versions/FlaskEnv/lib/python2.7/site-packages/var_dump/_var_dump.py", line 56, in dump
    display(o, space, num, key, typ)
  File "/home/bud/.pyenv/versions/FlaskEnv/lib/python2.7/site-packages/var_dump/_var_dump.py", line 45, in display
    l.append(len(o.__dict__))
AttributeError: 'weakref' object has no attribute '__dict__'

----------------------------------------------------------------------
Ran 1 test in 0.063s

FAILED (errors=1)

**Comment by sha256** [comment]
Fixed in 4eba56f67526c7b34b13c081003f75c6d8766969
