### ISSUE TITLE
Fails on sets - 'set' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by techtonik** [sha256/python-var-dump#8]
```
x = set([1,2,3])
from var_dump import var_dump
var_dump(x)
```
```
Traceback (most recent call last):
  File "dumpset.py", line 3, in <module>
    var_dump(x)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 79, in var_dump
    dump(x, 0, i, '', object)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 56, in dump
    display(o, space, num, key, typ)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 45, in display
    l.append(len(o.__dict__))
AttributeError: 'set' object has no attribute '__dict__'
```

**Comment by sha256** [comment]
Fixed in 4eba56f67526c7b34b13c081003f75c6d8766969
