### ISSUE TITLE
AttributeError: 'thread.lock' object has no attribute '__dict__' 

### ISSUE THREAD

**Issue by ManrajGrover** [sha256/python-var-dump#9]
Facing this issue on dumping an object. Please check.

```python 
Traceback (most recent call last):
  File "C:/Python27/test_dump.py", line 7, in <module>
    var_dump(r)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 79, in var_dump
    dump(x, 0, i, '', object)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 66, in dump
    dump(o[i], space, num, i, typ)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 66, in dump
    dump(o[i], space, num, i, typ)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 66, in dump
    dump(o[i], space, num, i, typ)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 56, in dump
    display(o, space, num, key, typ)
  File "C:\Python27\lib\site-packages\var_dump\_var_dump.py", line 45, in display
    l.append(len(o.__dict__))
AttributeError: 'thread.lock' object has no attribute '__dict__' 
```
How to reproduce? Please try this code.

```python
import requests
from var_dump import var_dump
r = requests.get('https://api.github.com/events')
var_dump(r)
```

**Comment by sha256** [comment]
fixed in 4eba56f67526c7b34b13c081003f75c6d8766969
